### ISSUE TITLE
How to include date and time infront of "Created" section in C++ template(template.ini file) which should be automatically inserted when I create .cpp file extension(Create Template Plugin)

### ISSUE THREAD

**Issue by piyush26c** [chronoxor/TrueTemplate#10]
Name="C++ program"
Ext="cpp"
{
"/**"
"*  Author:  Piyush Rajendra Chaudhari"         
"*  Created:"
"**/"
"#include <bits/stdc++.h>"
""
"using namespace std;"
""
"int main() {"
""
""
"  return 0;"
"}"
}

Above is the template code mentioned in the template.ini file in Create Plugin Folder in Far manager. Anybody can help me how should I fulfill my objective?

**Comment by chronoxor** [comment]
```
< Common current date/time >
Current Date     is : @@DATE@@
Current Time     is : @@TIME@@
Current DateTime is : @@DATETIME@@

< Formatted current date/time (see GetDateFormat/GetTimeFormat for details) >
Current day w/o leading zero ("d")     : @@DATE:d@@
Current day with leading zero ("dd")   : @@DATE:dd@@
Week day short name ("ddd")            : @@DATE:ddd@@
Week day full name ("dddd")            : @@DATE:dddd@@
Month w/o leading zero ("M")           : @@DATE:M@@
Month with leading zero ("MM")         : @@DATE:MM@@
Month short name ("MMM")               : @@DATE:MMM@@
Month full name ("MMMM")               : @@DATE:MMMM@@
Two digit year w/o leading zero ("y")  : @@DATE:y@@
Two digit year with leading zero("yy") : @@DATE:yy@@
Four digit year ("yyyy")               : @@DATE:yyyy@@
---------------------------------------
12-hour clock: Hour w/o leading zero  ("h")  : @@TIME:h@@
12-hour clock: Hour with leading zero ("hh") : @@TIME:hh@@
24-hour clock: Hour w/o leading zero  ("H")  : @@TIME:H@@
24-hour clock: Hour with leading zero ("HH") : @@TIME:HH@@
Minute w/o leading zero ("m")          : @@TIME:m@@
Minute with leading zero ("mm")        : @@TIME:mm@@
Second w/o leading zero ("s")          : @@TIME:s@@
Second with leading zero ("ss")        : @@TIME:ss@@
---------------------------------------
Formatted DateTime example 1            : @@DATETIME:yyyy/MM/dd hh\:mm\:ss@@
Formatted DateTime example 2            : @@DATETIME:dd-MM-yyyy HH\:mm\:ss@@
Formatted DateTime example 3            : @@DATETIME:dd MMMM yyyy HH\:mm\:ss@@
Formatted DateTime example 4            : @@DATETIME:(ddd) dd-MM-yyyy HH\:mm\:ss@@
Formatted DateTime example 5            : @@DATETIME:(ddd) dd'-'MM'-'yyyy HH'\:'mm'\:'ss@@
```

**Comment by chronoxor** [comment]
This TrueTemplate sample might be helpful:
https://raw.githubusercontent.com/chronoxor/TrueTemplate/master/templates/text/General%20test.tt

**Comment by piyush26c** [comment]
Thank you for your help 😊

**Comment by piyush26c** [comment]
when I wrote @@DATE@@in front of "Created:" far manager collapsed

**Comment by piyush26c** [comment]
I just want a template to write in front of the "Created:" so that when new .cpp file is created system date and time gets inserted on that position in .cpp file.

**Comment by s-gurman** [comment]
> This TrueTemplate sample might be helpful:
> https://raw.githubusercontent.com/chronoxor/TrueTemplate/master/templates/text/General%20test.tt

Недавно наткнулся на этот плагин, да и вбщ новичок в Far manager, поэтому прошу прощения за этот глупый вопрос, просто уже везде обыскался: Как добавить плагин в Far manager? Я разархивировал скачанный архив и полученное положил в папку %FarHome%/Plugins, перезагрузил Far, но в итоге плагин так и не появился в менеджере плагинов. Помогите, пожалуйста, если не сложно!

**Comment by chronoxor** [comment]
Попробуйте эту версию под FAR x64 - https://github.com/chronoxor/TrueTemplate/releases/download/3.0.2/TrueTemplate-3.0.2.zip

**Comment by s-gurman** [comment]
> Попробуйте эту версию под FAR x64 - https://github.com/chronoxor/TrueTemplate/releases/download/3.0.2/TrueTemplate-3.0.2.zip

Спасибо, помогло!
