### ISSUE TITLE
Query regarding importing template using True Template

### ISSUE THREAD

**Issue by piyush26c** [chronoxor/TrueTemplate#13]
I have included few templates of algorithms in FAR manager plugin called True template by making few changes in XML file. How I can import other templates that are stored in .cpp files with respective file names, inside the code written in preexisting .cpp file @chronoxor?

**Comment by ChanBong** [comment]
How are you using this in far manager ? As in can you explain how you "isntalled" it ?

**Comment by iyudincev** [comment]
> 
> 
> How are you using this in far manager ? As in can you explain how you "isntalled" it ?

Download the archive from [Releases](https://github.com/chronoxor/TrueTemplate/releases) and unzip it into Plugins\ subdirectory in FAR program files, then restart the app.

**Comment by ChanBong** [comment]
Yeah ! I got it
