### ISSUE TITLE
Code snippets in Far Manager

### ISSUE THREAD

**Issue by pankajm05** [chronoxor/TrueTemplate#15]
Hello, I have been searching for months but can't figure out how to use code snippets in Far using TrueTemplate. I saw Gennady (tourist, a famous competitive programmer) doing it in his streams where he would type a particular word in a CPP file (say Mint or digraph) and his template would get pasted there. That's what I am going for. Please help me @chronoxor, @iyudincev

**Comment by pankajm05** [comment]
An example: https://youtu.be/97tieEKfvBs?t=3561 Please help @chronoxor @iyudincev

**Comment by iyudincev** [comment]
You can find examples in `true-source-c++-base.xml`, see the `<Expand ... />` tags. Use `\i` to load a snippet from a file.
`<Expand Name="test" At="&OutWord;" SubMenu="1" Pattern="test" To="\i'$\templates\source\my-template.cpp'"/>`

**Comment by pankajm05** [comment]
Thanks a lot, It works now.

**Comment by prabh1805** [comment]
it's still not working for me
I used something lik this and in my c++ file when I am typing debug followed by enter it doesn't load my debug template

  <Expand Name="debugging"                At="&OutWord;" SubMenu="1" Pattern="debug|Debug"   To="\i'$\templates\source\debug.cpp'"/>

**Comment by ArnabGh16May** [comment]
This make the template but it is like that every time we have to open the plugin menu and insert it can't we add it just simply writing the name set by us as Gennady does    e.g. writing sieve will generate the code for sieve function created by us
